export const KNOWLEDGE_BASE: Record<string, string> = {
  "director": "### Office of the Director\n\nThe Director of **Netaji Subhas Institute of Technology (NSIT), Bihta**, is a distinguished academician and a visionary leader. Under their guidance, the institution has achieved significant milestones in technical education and research. The Director's office is committed to fostering an environment of innovation, discipline, and excellence.\n\nFor specific names, messages, and the latest administrative updates, we invite you to visit our official [About Us](https://www.nsit.in/about-us) page.",
  
  "principal": "### Principal's Desk\n\nThe Principal of NSIT Bihta plays a pivotal role in overseeing the academic operations, faculty development, and student welfare. With a focus on holistic development, the Principal ensures that the curriculum is delivered effectively and that students are prepared for the challenges of the professional world.\n\nDetailed information about the Principal and their vision can be found on the [Official Website](https://www.nsit.in/).",
  
  "location": "### Campus Location & Connectivity\n\n**Netaji Subhas Institute of Technology (NSIT)** is strategically located in the industrial hub of **Amhara, Bihta, Patna, Bihar - 801103**. \n\n*   **Connectivity:** The campus is well-connected by both road and rail. It is approximately 30 km from Patna Junction and is easily accessible via the Patna-Aurangabad highway.\n*   **Environment:** The campus offers a serene and conducive environment for learning, away from the hustle and bustle of the city, yet close enough to essential amenities.",
  
  "courses": "### Academic Programs Offered\n\nNSIT Bihta is renowned for its comprehensive technical programs. We offer **Bachelor of Technology (B.Tech)** degrees in the following core engineering branches:\n\n1.  **Computer Science & Engineering (CSE)**\n2.  **Electronics & Communication Engineering (ECE)**\n3.  **Mechanical Engineering (ME)**\n4.  **Civil Engineering (CE)**\n5.  **Electrical & Electronics Engineering (EEE)**\n\nAdditionally, our sister concern, **Netaji Subhas Institute of Polytechnic (NSIP)**, offers 3-year Diploma courses in various engineering disciplines.",
  
  "admission": "### Admission Procedure & Eligibility\n\nAdmission to the B.Tech program at NSIT Bihta is highly competitive and based on merit. \n\n*   **B.Tech Eligibility:** Candidates must have passed 10+2 (PCM) with a valid score in **JEE Main** or the **BCECE** entrance examination.\n*   **Diploma Eligibility:** Admission is based on the **DCECE** (Diploma Certificate Entrance Competitive Examination) conducted by BCECEB.\n*   **Enquiry:** Interested candidates can fill out the [Online Enquiry Form](https://www.nsit.in/enquiry) to receive a call from our admission counselors.",
  
  "fees": "### Fee Structure & Financial Information\n\nAt NSIT Bihta, we strive to provide high-quality education at an affordable cost. The fee structure is designed to be transparent and covers tuition, laboratory, and library facilities.\n\n*   **Updates:** Fee structures are subject to periodic reviews by the management and university.\n*   **Contact:** For the most accurate and current fee details for the 2024-25 session, please contact our **Admission Cell at 7781020364** or visit the campus administrative office.",
  
  "placement": "### Training & Placement Cell\n\nOur dedicated **Training & Placement (T&P) Cell** works tirelessly to bridge the gap between academia and industry. \n\n*   **Recruiters:** Top-tier companies like **TCS, Infosys, Wipro, Capgemini, and HCL** regularly visit our campus for recruitment drives.\n*   **Preparation:** We provide extensive training in soft skills, aptitude, and technical interviews to ensure our students are 'industry-ready'.\n*   **Success:** Our alumni are successfully placed in leading MNCs across the globe, reflecting the quality of education at NSIT.",
  
  "hostel": "### Residential Facilities (Hostels)\n\nNSIT Bihta offers a 'home away from home' experience with its modern residential facilities.\n\n*   **Separate Wings:** We have separate, secure hostel buildings for boys and girls.\n*   **Amenities:** Each hostel is equipped with high-speed Wi-Fi, 24/7 power backup, clean drinking water (RO), and a common room for recreation.\n*   **Mess:** The hostel mess provides nutritious and hygienic vegetarian and non-vegetarian meals.",
  
  "contact": "### Contact Information\n\nFor any queries regarding admissions, academics, or general information, please feel free to reach out to us:\n\n*   **Email:** info@nsit.in\n*   **Phone:** +91 7781020364 / 7781020346\n*   **Address:** Amhara, Bihta, Patna, Bihar - 801103\n*   **Social Media:** Follow us on Facebook and Instagram for the latest campus news.",
  
  "website": "### Official Digital Presence\n\nThe only official website for Netaji Subhas Institute of Technology, Bihta, is **[https://www.nsit.in/](https://www.nsit.in/)**. We advise all students and parents to rely only on this website for authentic information regarding notices, results, and events.",
  
  "ragging": "### Anti-Ragging Policy\n\nNSIT Bihta maintains a **Zero Tolerance Policy** towards ragging. We strictly adhere to the guidelines set by the **AICTE, UGC, and the Hon'ble Supreme Court of India**.\n\n*   **Anti-Ragging Squad:** A dedicated committee and squad monitor the campus 24/7 to ensure a safe and welcoming environment for freshers.\n*   **Reporting:** Any instance of ragging can be reported immediately to the Principal or the Anti-Ragging Committee.",
  
  "transport": "### Transportation Services\n\nTo facilitate easy commuting for students and staff, the college operates a fleet of buses covering major routes across **Patna, Danapur, Khagaul, and Bihta**.\n\n*   **Safety:** Our buses are well-maintained and driven by experienced staff.\n*   **Punctuality:** The transport department ensures timely arrival and departure from the campus.",
  
  "library": "### Central Library & Digital Resources\n\nThe Central Library at NSIT is a treasure trove of knowledge, housing over **20,000+ volumes** of books, national and international journals, and periodicals.\n\n*   **Digital Library:** Students have access to e-journals and digital databases to support their research and projects.\n*   **Reading Room:** A spacious and quiet reading room is available for students to study during and after college hours.",
  
  "wifi": "### Smart Campus & Wi-Fi\n\nNSIT Bihta is a fully **Wi-Fi enabled campus**. We provide high-speed internet connectivity to all academic blocks, laboratories, and hostels to ensure that students have access to global information at their fingertips.",
  
  "scholarship": "### Scholarships & Financial Aid\n\nWe believe that financial constraints should not hinder a student's education. \n\n*   **Government Schemes:** Eligible students can apply for the **Bihar Post-Matric Scholarship**, **National Scholarship Portal (NSP)** schemes, and the **Bihar Student Credit Card** scheme.\n*   **Assistance:** Our administrative office provides full support to students in the documentation process for these scholarships.",
  
  "btech": "### B.Tech (Bachelor of Technology)\n\nThe B.Tech program at NSIT is a **4-year full-time degree course** affiliated with **Aryabhatta Knowledge University (AKU)** and approved by **AICTE**.\n\n*   **Specializations:** CSE, ECE, ME, CE, EEE.\n*   **Focus:** The curriculum is designed to provide a strong foundation in engineering principles combined with practical laboratory experience.",
  
  "diploma": "### Diploma in Engineering (Polytechnic)\n\nOffered by our sister concern **Netaji Subhas Institute of Polytechnic (NSIP)**, the Diploma is a **3-year course** affiliated with **SBTE Bihar**.\n\n*   **Eligibility:** 10th pass from a recognized board.\n*   **Pathway:** Diploma holders can also opt for Lateral Entry into the 2nd year of the B.Tech program at NSIT.",
  
  "cse": "### Computer Science & Engineering (CSE)\n\nThe **CSE Department** at NSIT is equipped with advanced computer labs featuring the latest software and high-speed servers.\n\n*   **Curriculum:** Focuses on AI, Machine Learning, Data Science, and Software Engineering.\n*   **Placements:** CSE students consistently secure the highest placement packages in top IT firms.",
  
  "mechanical": "### Mechanical Engineering (ME)\n\nThe **Mechanical Engineering Department** boasts state-of-the-art workshops, including CNC machines, thermal engineering labs, and fluid mechanics labs.\n\n*   **Practical Learning:** Students engage in hands-on projects, including automobile design and robotics.",
  
  "civil": "### Civil Engineering (CE)\n\nOur **Civil Engineering Department** provides students with exposure to modern surveying techniques, structural analysis software, and material testing laboratories.\n\n*   **Field Work:** Regular site visits and industrial tours are organized to give students a real-world perspective of the construction industry.",
  
  "electrical": "### Electrical & Electronics Engineering (EEE)\n\nThe **EEE Department** focuses on power systems, electrical machines, and control engineering. \n\n*   **Labs:** Well-equipped with high-voltage testing kits and advanced simulation tools.",
  
  "electronics": "### Electronics & Communication Engineering (ECE)\n\nThe **ECE Department** covers the latest trends in communication systems, VLSI design, and embedded systems.\n\n*   **Innovation:** Students are encouraged to work on IoT and wireless communication projects in our specialized labs.",
  
  "tour": "### Virtual Campus Tour\n\nExperience the NSIT Bihta campus from the comfort of your home! Our **Virtual Tour** provides a 360-degree view of our state-of-the-art infrastructure, including academic blocks, laboratories, hostels, and sports facilities.\n\n*   **Start the Tour:** [Click here to begin your Virtual Tour](https://www.nsit.in/tour)\n*   **Highlights:** Explore our lush green campus, advanced engineering workshops, and modern residential wings."
};

